version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: sqump_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: sqump_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "sqump_zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT
      KAFKA_LISTENERS: CLIENT://:9092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
