# See: https://github.com/golangci/golangci-lint-action
name: lint
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with: 
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=90s
